$ANSIBLE_VAULT;1.1;AES256
35366630393965373233393931646533636330303462393165343938313237343266376631356633
3035376235656138363437663036383137666635653334370a336665316434633732643033396164
65623633396135633434613364356539383932613264333739623133623932326464326236396530
6463373333313031610a613531323332386137613565633064636366623966613036353933373332
33363464636239633562326339613032343239656433323166393131303337313238363439326161
6636333562336363653536323539366438396233303139303032
